<?php
/**
 * @category   Gabi77
 * @package    Gabi77_Eulerian
 * @copyright  Copyright (c) 2014 Gabi77 (http://www.gabi77.com)
 * @author     Gabriel Janez <contact@gabi77.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

$customer = Mage::getSingleton('customer/session')->getCustomer();
$email 	= $customer->getEmail();	// Email Client
$id 	= $customer->getId();		// Id Client
$param	= "";
?>
<!-- Eulerian Analytics -  / tag -->
<script type="text/javascript">
/*<![CDATA[*/
var EA_data = [
	'email','<?php echo $email; ?>',
	'estimate','1',
	'type','client',
	'uid','<?php echo $id; ?>',
	'path','create_account'
]);
/*]]>*/
</script>
<?php echo Mage::helper('gabi77_eulerian/eulerian')->getEulerianIframe($param); ?>
<!-- /Eulerian Analytics -  / tag -->

