<?php
/**
 * @category   Gabi77
 * @package    Gabi77_Eulerian
 * @copyright  Copyright (c) 2014 Gabi77 (http://www.gabi77.com)
 * @author     Gabriel Janez <contact@gabi77.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

$customer = Mage::getSingleton('customer/session')->getCustomer();
$email 	= $customer->getEmail();	// Email Client
$id 	= $customer->getId();		// Id Client
/** ancienne version **/
$path = parse_url(Mage::helper('core/url')->getCurrentUrl(),PHP_URL_PATH);
$path = Mage::app()->getFrontController()->getAction()->getFullActionName();
$param = 'path='.$path;
?>
<!-- Eulerian Analytics -  / tag -->
<script type="text/javascript">
/*<![CDATA[*/
var EA_data = [
			   'path',	'<?php echo $path; ?>'
];
(function(){var td='<?php echo Mage::helper('gabi77_eulerian/eulerian')->getEulerianUrl(); ?>',d=document,l=d.location;if(!l.protocol.indexOf('http')){var o=d.createElement('script'),a=d.getElementsByTagName('script')[0],cn=parseInt((new Date()).getTime()/3600000),cj='',cdh=(l.host+td).replace(/[^a-z]/g,''),cdr=cdh+cdh.toUpperCase(),acdr=cdr.split('');for(var i=-1;i<cn%7;i++){cj+=acdr[(cn+i)%acdr.length];}o.type='text/javascript';o.async='async';o.defer='defer';o.src='//'+td+'/'+cj+(cn%8760)+'.js';a.parentNode.insertBefore(o,a);}})();
/*]]>*/
</script>
<?php echo Mage::helper('gabi77_eulerian/eulerian')->getEulerianIframe($param); ?>

<!-- /Eulerian Analytics -  / tag -->

